# TensorRT-Redux nodes
from .export_engine import TRT_MODEL_EXPORT
from .export_lora import TRT_LORA_EXPORT, TRT_LORA_EXPORT_FROM_MODEL
from .loader import TRT_LOADER_LORA, TRT_LORA_STACK, TRT_LOADER_LORA_STACKED

NODE_CLASS_MAPPINGS = {
    "TRT_MODEL_EXPORT": TRT_MODEL_EXPORT,
    "TRT_LORA_EXPORT": TRT_LORA_EXPORT,
    "TRT_LORA_EXPORT_FROM_MODEL": TRT_LORA_EXPORT_FROM_MODEL,
    "TRT_LOADER_LORA": TRT_LOADER_LORA,
    "TRT_LORA_STACK": TRT_LORA_STACK,
    "TRT_LOADER_LORA_STACKED": TRT_LOADER_LORA_STACKED,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "TRT_MODEL_EXPORT": "TensorRT Model Export (LoRA-Ready)",
    "TRT_LORA_EXPORT": "TensorRT LoRA Export",
    "TRT_LORA_EXPORT_FROM_MODEL": "TensorRT LoRA Export (From Model)",
    "TRT_LOADER_LORA": "TensorRT Loader + LoRA",
    "TRT_LORA_STACK": "TensorRT LoRA Stack",
    "TRT_LOADER_LORA_STACKED": "TensorRT Loader + Stacked LoRAs",
}
